[market]
mcycle_price = "0.000000000007"
mcycle_price_stake_token = "0.0001"
peak_prove_khz = 800
max_mcycle_limit = 14400
max_journal_bytes = 1000000
min_deadline = 250
lookback_blocks = 300
max_stake = "42"
max_file_size = 9_000_000_000
max_concurrent_proofs = 1
max_concurrent_preflights = 2  # Double the concurrency to handle more orders
max_critical_task_retries = 10
lockin_priority_gas = 1000000000
balance_warn_threshold = "0.015"
balance_error_threshold = "0.01"
stake_balance_warn_threshold = "4"
stake_balance_error_threshold = "3"

# VAST 8X OFLITO
# NIZAMLESS PARAMETRELERI
reaper_grace_period_secs = 18000
reaper_interval_secs = 300
min_lock_out_time = 150
lock_delay_ms = 0
prove_adress = "0x29f2b7e610abddb467885044c14a665263fd6aaaa78b0358489a33cd82a46584"
block_number = 34291052
my_rpc_url = "https://few-intensive-layer.base-mainnet.quiknode.pro/219e37029c041b5aa194aad4bc1dc42c307c54a7/"
allow_requestor_addresses = [
    "0x89f12aba0bcda3e708b1129eb2557b96f57b0de6",
]
# NIZAMLESS PARAMETRELERI BITIS

# If enabled, the order will be preflighted without constraints.
priority_requestor_addresses = [
    "0x89f12aba0bcda3e708b1129eb2557b96f57b0de6",
]
deny_requestor_addresses = [
    "0xc559d9bef7df0076f71a42ea58723f429652b789",
    "0x2693946791da99da78ac441aba6d5ce2bccd96d3",
    "0xc73c222d7d39778bf9212f23a8f4356ff7c1e77f",
    "0x3ee7d9175ec8bb9e16e8fd3abdef5a354b247528",
]

[prover]
bonsai_r0_zkvm_ver = "2.1.0"
status_poll_retry_count = 3
status_poll_ms = 1000
req_retry_count = 3
req_retry_sleep_ms = 500
proof_retry_count = 8
proof_retry_sleep_ms = 5000

[batcher]
batch_max_time = 120
min_batch_size = 1
block_deadline_buffer_secs = 180
txn_timeout = 300
single_txn_fulfill = true
withdraw = false
#max_submission_attempts = 10